import { createSlice } from '@reduxjs/toolkit';
import {
  Gwen,
  Senna,
  Lucian,
  Black,
  Viego,
  allNG,
  GwenNG,
  CatNG,
  RivenNG,
  GarenNG,
  ReketonNG,
  LucianNG,
  SamiraNG,
  SennaNG,
  ViegoNG,
  VolibearNG,
  HasagePlayNG,
  YoneNG,
} from '../../assets/characters';

type sentence = {
  name: string;
  secondPerson?: boolean;
  isSecondMain?: boolean;
  image: string;
  secondImage?: string;
  position: string;
  secondPosition?: string;
  bg: string;
  text: string;
};

type initialstate = {
  sentences: sentence[];
};

const initialState: initialstate = {
  sentences: [
    {
      name: 'Сенна',
      image: Senna,
      position: 'left',
      bg: 'ViegoFall',

      text: ' - Думаешь, это хорошая идея?',
    },
    {
      name: 'Люциан (Перебивая)',
      image: Lucian,
      position: 'right',
      bg: 'ViegoFall',

      text: ' - Определённо плохая! Вы забыли, чем всё обернулось в прошлый раз!?',
    },
    {
      name: 'Гвен',
      image: Gwen,
      position: 'left',
      bg: 'ViegoFall',

      text: ' - Мне тоже тревожно, но попробовать стоит. В нём определено сохранилось что-то хорошее, нужно просто это пробудить! В этот раз всё будет иначе!',
    },
    {
      name: 'Люциан',
      image: Lucian,
      position: 'right',
      bg: 'ViegoFall',

      text: ' - Ни чем хорошим это не закончится...',
    },
    {
      name: 'Гвен',
      image: Gwen,
      position: 'left',
      bg: 'ViegoFall',
      text: ' - Да ладно тебе, Люциан. Его ненависть - это недостаток любви. Ему очень больно. Мы должны попробовать!',
    },
    {
      name: 'Сенна',
      image: Senna,
      position: 'left',
      bg: 'ViegoFall',

      text: ' - Я могу его понять, Люциан, да и ты тоже. Кому, как не тебе знать тяжесть разлуки?',
    },
    {
      name: 'Люциан',
      image: Lucian,
      position: 'right',
      bg: 'ViegoFall',

      text: ' - Но я, в отличие от него, не превратился в чудовище!',
    },
    {
      name: 'Сенна',
      image: Senna,
      position: 'left',
      bg: 'ViegoFall',

      text: ' - Да, ты сильнее. Поэтому мы и должны помочь. Такой участи не заслужил никто.',
    },
    {
      name: 'Люциан',
      image: Lucian,
      position: 'right',
      bg: 'ViegoFall',

      text: ' - Плохая идея...',
    },
    {
      name: 'Гвен',
      image: Gwen,
      position: 'left',
      bg: 'ViegoFall',

      text: ' - Итак, приготовьтесь!',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',

      text: '...',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',

      text: 'Перед входной дверью...',
    },
    {
      name: 'Гвен',
      image: Gwen,
      bg: 'winterHome',
      position: 'left',

      text: ' - Итак, ты готов? Помнишь наш разговор?',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'winterHome',
      position: 'right',

      text: ' - Это издевательство над королём! Туман струится из моей груди не для того, чтобы... ',
    },
    {
      name: 'Гвен',
      image: Gwen,
      bg: 'winterHome',
      position: 'left',

      text: ' - Тем более, это цена твоего освобождения. Ты всё ещё можешь стать лучше... Ты должен ради неё.',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'winterHome',
      position: 'right',

      text: ' - Я - падший король! Несколько добрых дел не вернут мою любимую к жизни.',
    },
    {
      name: 'Гвен',
      image: Gwen,
      bg: 'winterHome',
      position: 'left',

      text: ' - Да, но... вспомни её. Изольда бы хотела именно этого! Почти её память деяниями, Виего. Докажи нам всем, что выбор её сердца - лучший выбор.',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'winterHome',
      position: 'right',

      text: ' - Смогу ли я?',
    },
    {
      name: 'Гвен',
      image: Gwen,
      bg: 'winterHome',
      position: 'left',

      text: ' - Я в тебя верю. Все мы верим в тебя, Виего. Давай!',
    },
    {
      name: 'Виего(Обращаясь к закату)',
      image: Viego,
      bg: 'winterHome',
      position: 'right',

      text: ' - Любимая, я иду на это ради тебя...',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',

      text: '...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',

      text: ' - Добро пожаловать, это новогодний дом Рунтерры! ',
    },
    {
      name: 'Все',
      image: allNG,
      bg: 'homeInside',
      position: 'full',

      text: '(поворачиваются)',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'right',

      text: '(оглядывается)',
    },
    {
      name: 'Все',
      image: allNG,
      bg: 'homeInside',
      position: 'full',

      text: '(негодуют)',
    },
    {
      name: 'Гвен(шепотом)',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',

      text: ' - Виего, скажи что-нибудь!',
    },
    {
      name: 'Люциан',
      image: Lucian,
      bg: 'homeInside',
      position: 'right',

      text: ' - Это плохая идея...',
    },
    {
      name: 'Виего(неуверенно)',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' - Приветствую всех собравшихся под этой крышей!',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' - Я польщён вашим милосердием и знаю об условии моего освобождения... ',
    },
    {
      name: 'Люциан',
      image: Lucian,
      bg: 'homeInside',
      position: 'right',

      text: ' - Это не милосердие, а элементарная глупость!',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' - В прошлый раз я был сражён идеей воскрешения любимой и, будучи жестоким, захватывал одни земли за другими...',
    },
    {
      name: 'Виего(искренне)',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' -  Теперь мои глаза открыты.',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' - У вас нет причины доверять или понимать меня, но в предверии праздника я постараюсь стать тем, кем бы меня хотела Видеть Изольда и кем когда-то был я сам. ',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'center',

      text: ' - Хорошим человеком.',
    },
    {
      name: 'Гвен (Аккуратно)',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Если новый год - действительно время чудес, то почему бы нам не поспособствовать и этому... Чуду?',
    },
    {
      name: 'Юми (Пренебрежительно)',
      image: CatNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Как ты думаешь, Книга, призраки умеют чесать за ушком?',
    },
    {
      name: 'Ривен (Искренне)',
      image: RivenNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Каждый заслуживает получить второй шанс. Пусть попробует, я не против.',
    },
    {
      name: 'Гарен (По',
      image: GarenNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Не забывайте о его деяниях, друзья! К такому... призраку стоит отностится с особой осторожностью. Сомневаюсь, что он может хоть как-то измениться!',
    },
    {
      name: 'Рекетон (Рекетон)',
      image: ReketonNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Арр!!! Я ему не верю! Ррррррррр!!!',
    },
    {
      name: 'Самира (С усмешкой)',
      image: SamiraNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - А что, звучит весело! Если принесет мне Арбалет на 10 минуте, то пусть остается!',
    },
    {
      name: 'Ёне',
      image: YoneNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Прощение нужно заслужить, но его заслуживает не каждый...',
    },
    {
      name: 'Люциан (Сурово)',
      image: LucianNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Мое мнение вы знаете.',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Эх, кому, как не мне, знать это бремя...',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'center',
      text: '...',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Ой, это не моя сцена!',
    },
    {
      name: 'Все',
      image: allNG,
      bg: 'homeInside',
      position: 'full',
      text: '...',
    },
    {
      name: 'Все',
      image: allNG,
      bg: 'homeInside',
      position: 'full',
      text: '... ...',
    },
    {
      name: 'Волибир',
      image: VolibearNG,
      bg: 'homeInside',
      position: 'center',
      text: 'А я, между прочем, сама Буря!',
    },
    {
      name: 'Волибир',
      image: VolibearNG,
      bg: 'homeInside',
      position: 'center',
      text: 'Представляете?)',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'homeInside',
      position: 'right',
      text: '...',
    },
    {
      name: 'Ёне',
      image: YoneNG,
      bg: 'homeInside',
      position: 'left',
      text: 'Я с ними разберусь, продолжайте.',
    },
    {
      name: 'Сенна',
      image: SennaNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Виего натворил достаточно дел, но если он действительно готов и хочет измениться, то нужно дать ему шанс.',
    },
    {
      name: 'Сенна',
      image: SennaNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Я за.',
    },
    {
      name: 'Ривен',
      image: RivenNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Я тоже.',
    },
    {
      name: 'Юми',
      image: CatNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Мы с книгой не против. Мяу.',
    },
    {
      name: 'Самира',
      image: SamiraNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Я готова посмеяться!',
    },
    {
      name: 'Рекетон',
      image: ReketonNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Ар.... Арррр....ррррррр...рр! Да.',
    },
    {
      name: 'Гарен',
      image: GarenNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Хорошо, но я буду начеку!',
    },
    {
      name: 'Волибир',
      image: VolibearNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Я согласен!!!',
    },
    {
      name: 'Ёне',
      image: YoneNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Ок...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Я готова!',
    },
    {
      name: 'Люциан (Хладнокровно)',
      image: LucianNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Я против.',
    },
    {
      name: 'Люциан (Раздраженно)',
      image: LucianNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Не понимаю, как вы можете ему доверять.',
    },
    {
      name: 'Гвен (Хрустально)',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - А как же чудо Нового года, Люциан? Да, сделано было много, но это в прошлом.',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Поверь в него, как в новогоднее чудо! На этот раз все будет иначе.',
    },
    {
      name: 'Сенна (Искренне)',
      image: SennaNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Люциан, давай.',
    },
    {
      name: 'Люциан',
      image: LucianNG,
      bg: 'homeInside',
      position: 'right',
      text: ' - Хорошо. Ваша воля.',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'street',
      position: 'right',
      text: ' - Значт мне нужно заполучить близкую каждому гостю вещь и приподнести до полуночи?',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'street',
      position: 'right',
      text: ' - Хорошо, но куда пойти, дабы мои поиски увенчались успехом?',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'street',
      position: 'right',
      text: ' - Любимая, знала бы ты, как это тяжело...',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Она бы тебя поддержала. И я поддерживаю. Ты делаешь правльное и доброе дело!',
    },
    {
      name: 'Виего (Пусто)',
      secondPerson: true,
      isSecondMain: false,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Честно говоря, я совсем не чуствую предстоящего торжества.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Почувствуешь, когда станешь его частью!',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Новый год - это просто дата. Праздник создают люди.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - И крокодилы.',
    },
    {
      name: 'Виего (Смущенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - ...',
    },
    {
      name: 'Виего (Вскользь)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Спасибо, что вызвалась мне помогать.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Пустяки. Просто...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' -  Просто что?',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Она бы этого хотела.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - ...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Хочется верить, что после содеянного ей было бы не все равно.',
    },
    {
      name: 'Гвен (Серьезно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Ты найдешь свой покой, Виего. Обещаю.',
    },
    {
      name: 'Виего (Кивая)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      bg: 'street',
      position: 'right',
      secondPosition: 'left',
      text: ' - Эх, Изольда...  Что же меня ждет?',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'libraryShop',
      position: 'left',
      text: ' - Книжная лавка? Интересно.',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'libraryShop',
      position: 'left',
      text: ' - Что ты придумал, Виего?',
    },
    {
      name: 'Виего (Уверенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Среди всех приглашенных гостей только один человек, не считая тебя и Сенны, сразу принял меня и мои ошибки.',
    },
    {
      name: 'Виего (Уверенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Я должен угодить всем, но начать хочу с подарка для нее.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - О ком ты говоришь?',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - О Ривен.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Такому человеку нужен скромный, но элегантный, поистине насыщенный подарок, заставляющий обладателя возвращаться вновь и вновь в погоне за теплыми чувствами и необъятными мыслями. ',
    },
    {
      name: 'Виего (Уверенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Я хочу подарить ей книгу - книгу о ее Родине.',
    },
    {
      name: 'Виего (Уверенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - О Демасии.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - ...',
    },
    {
      name: 'Гвен (Тупо)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Виего %6?4@ь.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Да?',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Ривен... Она из Ионии.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - А. Пон. Ну ок. (((',
    },
    {
      name: 'Гвен (Восхищенно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' -Но, так или иначе, это явный шаг в сторону света! Я тобой горжусь.',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Какую именно книгу ты хочешь ей подарить?',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'libraryShop',
      text: ' - Есть одна идея...',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Гвен (Дразня)',
      image: GwenNG,
      bg: 'street',
      position: 'left',
      text: ' - Эх, Виего-Виего...',
    },
    {
      name: 'Гвен (Дразня)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Так много гордости, столько власти, а по итогу...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Это просто недоразумение!',
    },
    {
      name: 'Гвен (Передразнивая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - "Это просто недоразумение!" ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Великий упавший Король, захвативший практически всю Рунтерру... ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Подчинивший сильнейших воинов... ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Практичнески свершивший необратимое... ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - ... ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Не смог оплатить покупку на кассе. ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - ... ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Придуманная вами валюта... Смешна и глупа. Кто придумал эти... RP!? ',
    },
    {
      name: 'Гвен (Смеясь)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Король-король, в кармане ноль! Кстати, с тебя должок! ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Ладно, но... об этому никому! ',
    },
    {
      name: 'Гвен (Смеясь)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Ахпхпхапхапх. Хорошо.',
    },
    {
      name: 'Гвен (Смеясь)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Куда направимся теперь?',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - ...',
    },
    {
      name: 'Виего (Задумчиво)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Сейчас я думаю об одной гостье... Подобрать ей подарок не составит особого труда.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Мы идем за подушкой, Гвен. Нам нужна подушка!',
    },
    {
      name: 'Гвен (Понимая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - А...',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',

      text: ' - Я - падший Король! Вы не имеете права мне отказывать! ',
    },
    {
      name: 'Кассир (В страхе)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - Но... ',
    },
    {
      name: 'Виего (Агрессивно)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Я не потерплю возражений! Вы выполните мою просьбу или лишитесь голов!',
    },
    {
      name: 'Виего (Агрессивно)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Ваши проблемы ничтожны по сравнению с моей миссией, моим искуплением!',
    },
    {
      name: 'Кассир (В страхе)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - ...',
    },
    {
      name: 'Виего (Агрессивно)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Не желаю ничего знать о RP! Подйте мне то, чего я хочу! Сейчас же! ',
    },
    {
      name: 'Гвен (Сражена)',
      image: GwenNG,
      bg: 'catShop',
      position: 'left',
      text: ' - Виего...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Подожди, Гвен. Мне кажется, они не ведают о назаказании, которое следует за пренебрежением воли короля!',
    },
    {
      name: 'Кассир (Дрожа)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - Пожалуйста, успокойте этого психованного...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Да как ты смеешь? Я - падший Король!',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Ты не осознаешь тяжести поставленного на кон! Я иду по пути искупления...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Мне нужна эта подушка! Отдайте ее или познаете гнев Погибели!',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'catShop',
      position: 'left',
      text: ' - ...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'catShop',
      position: 'left',
      text: ' - Успокойтесь, пожалуйста, он просто не в себе...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      bg: 'catShop',
      position: 'left',
      text: ' - Я за все заплачу...',
    },
    {
      name: 'Кассир (Дрожа)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - Ничего страшного... Забирайте так...',
    },
    {
      name: 'Виего',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - И только попробуйте забыть про упаковку! Я сдам в вас весь прокаст!',
    },
    {
      name: 'Кассир (Дрожа)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - П...',
    },
    {
      name: 'Кассир (Дрожа)',
      image: undefined,
      bg: 'catShop',
      position: 'left',
      text: ' - П...пожалуйста... П...приходите еще...',
    },
    {
      name: 'Виего (Довольно)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Ну вот! Теперь воля Короля исполнена.',
    },
    {
      name: 'Виего (Довольно)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Гвен, мы получили то, за чем пришли! Уходим!',
    },
    {
      name: 'Виего (Гордо)',
      image: Viego,
      bg: 'catShop',
      position: 'center',
      text: ' - Ох, да! Я уже чувствую, как мое тело пробирает доброта! Да...',
    },
    {
      name: 'Гвен (Испанский стыд)',
      image: GwenNG,
      bg: 'catShop',
      position: 'left',
      text: ' - Ох, Виего...',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Гвен (Не удивляясь)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Виего!',
    },
    {
      name: 'Виего (Довольный собой)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Да, Гвен?',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - ...',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Ты должен мне еще 950 RP.',
    },
    {
      name: 'Виего (Радостно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Ох, это пустяки! Я все-таки Король!',
    },
    {
      name: 'Виего (Радостно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Наш путь еще не окончен! Я должен заполучить подарки для каждого гостя!',
    },
    {
      name: 'Гвен (Аккуратно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - И... Какими же методами ты собрался их "Заполучать"?',
    },
    {
      name: 'Виего (Ехидно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Все просто, Гвен! Я же Король! Ах, ну и, конечно же... ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Смею предположить, что мне понадобятся твои RP. ',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Ох, Виего... ',
    },
    {
      name: 'Виего (Самодовольно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - Тише, Гвен! Я иду по пути искупления и добра!',
    },
    {
      name: 'Гвен (Укоризненно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'street',
      text: ' - ... ',
    },
    {
      name: '...',
      image: Black,
      bg: 'Black',
      position: 'left',
      text: '...',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'street',
      position: 'right',
      text: 'Вдохновленный собственными победами, Виего продолжал посещать незнакомые места, залезая в еще большие долги. Гвен всюду следовала за ним, зачастую воздерживаясь от комментариев. Благо, ее RP хватало на все идеи Короля.',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'street',
      position: 'right',
      text: 'Иногда они оказывались действительно хорошими...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'samiraGift',
      text: ' - Я уверен, Самире понравится этот подарок! ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'samiraGift',
      text: ' - Я обратил внимание на ее некоторые черты и, кажется, угадал стиль...',
    },
    {
      name: 'Гвен (Радостно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'samiraGift',
      text: ' - Виего, это прекрасно! Даже я не смогла придумать бы лучше! ',
    },
    {
      name: 'Гвен (Радостно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'samiraGift',
      text: ' - Самира будет в восторге!',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'street',
      position: 'right',
      text: 'Но были и такие, о которых хотелось забыть...',
    },
    {
      name: 'Гвен (Агрессивно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Виего! Отпусти бездомного! ',
    },
    {
      name: 'Гвен (Агрессивно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Для Рекетона можно найти более подходящий подарок! ',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Да брось, Гвен, это же чистое мясо! ',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Уверен, мы с Рекетоном станем лучшими друзьями! ',
    },
    {
      name: 'Виего (Пренебрежительно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Он все равно почти мертв!',
    },
    {
      name: 'Гвен (Агрессивно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'reketonsGift',
      text: ' - Виего, нет! ',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'street',
      position: 'right',
      text: 'Путем экспериментов, неловкости, чередования и удивительных решений наши герои собрали все необходимые подарки. Виего так гордился собой, что и думать забыл о темноте, в которой когда-то существовал.',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'street',
      position: 'right',
      text: 'Гвен... Гвен просто ходила следом и оплачивала "Идеи" Виего, отговаривая от некоторых их них. Гвен порядком... устала.',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'winterHome',
      position: 'right',
      text: 'Ближе к полуночи наше герои вернулись в новогодний дом Рунтерры.',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'winterHome',
      position: 'right',
      text: 'Виего был в предвкушении праздника. Гвен была... уставшей.',
    },
    {
      name: 'Рекетон',
      secondPerson: true,
      isSecondMain: true,
      image: SamiraNG,
      secondImage: ReketonNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Аррр....Рр...... Арр...Аррррр!',
    },
    {
      name: 'Самира (Вовлеченная)',
      secondPerson: true,
      isSecondMain: !true,
      image: SamiraNG,
      secondImage: ReketonNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Хахпахпахпх! Серьезно!? Так и сказал?!',
    },
    {
      name: 'Рекетон',
      secondPerson: true,
      isSecondMain: true,
      image: SamiraNG,
      secondImage: ReketonNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - АРРРРР! Арарара! Ар.....РАААА!',
    },
    {
      name: 'Самира (В слезах)',
      secondPerson: true,
      isSecondMain: !true,
      image: SamiraNG,
      secondImage: ReketonNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Хахпахпахпх! Не могу поверить!',
    },
    {
      name: 'Ривен',
      secondPerson: true,
      isSecondMain: !true,
      image: RivenNG,
      secondImage: YoneNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - А что ты думаешь об этом, Ёне?',
    },
    {
      name: '1000-7',
      secondPerson: true,
      isSecondMain: true,
      image: RivenNG,
      secondImage: YoneNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Кто видел много - говорит мало, кто видел мало - говорит: "Я мало видел"...',
    },
    {
      name: 'Ривен',
      secondPerson: true,
      isSecondMain: !true,
      image: RivenNG,
      secondImage: YoneNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Блин, умно...',
    },
    {
      name: '1000-7',
      secondPerson: true,
      isSecondMain: true,
      image: RivenNG,
      secondImage: YoneNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Будь тем, кто ты есть... Не будь тем, кто ты нет...',
    },
    {
      name: 'Ривен',
      secondPerson: true,
      isSecondMain: !true,
      image: RivenNG,
      secondImage: YoneNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Аааааа....... Со смыслом...',
    },
    {
      name: 'Волибир',
      image: VolibearNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - А я все еще сама Буря!',
    },
    {
      name: 'Волибир',
      image: VolibearNG,
      bg: 'homeInside',
      position: 'center',
      text: ' - Хе-хе!',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Кажется, в этом рассказе нет моей сцены...',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Блин...',
    },
    {
      name: 'Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - У меня...',
    },
    {
      name: ' Хасаге',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Нет проблем, кроме моей бошки... Я умер, прости...',
    },
    {
      name: 'Рассказчик',
      image: undefined,
      bg: 'winterHome',
      position: 'right',
      text: ' - Все протекало своим чередом, пока наши герои не вошли в дверь...',
    },
    {
      name: 'Гвен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Друзья, мы вернулись!',
    },
    {
      name: 'Все',
      image: allNG,
      bg: 'homeInside',
      position: 'full',
      text: '...',
    },
    {
      name: 'Юми (Безразлично)',
      secondPerson: true,
      isSecondMain: true,
      image: RivenNG,
      secondImage: CatNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Книга, посмотри! Призрак вернулся с Гвен!',
    },
    {
      name: 'Ривен (Одобрительно)',
      secondPerson: true,
      isSecondMain: !true,
      image: RivenNG,
      secondImage: CatNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ты успел к сроку, Виего! Молодец.',
    },
    {
      name: 'Гвен (Уставшая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Молодец, Виего! Постарался на славу, %3*#ть...',
    },
    {
      name: 'Виего (Торжественно)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Здравствуйте, гости!',
    },
    {
      name: ' Хасаге (В стороне)',
      image: HasagePlayNG,
      bg: 'homeInside',
      position: 'left',
      text: ' - Ай, не надо, Ай, бросьте...',
    },
    {
      name: 'Виего',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Гвен',
      image: GwenNG,
      position: 'left',
      bg: 'homeInside',
      text: ' - Не обращай внимания. Мы его выгнать не можем - там холодно очень. По весне сам уйдет...',
    },
    {
      name: 'Виего (Величественно)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Итак! Я - Король, и я держу свое слово. Вы дали мне шанс на искупление, вы поверили в меня, и я намерен ваше доверие оправдать!',
    },
    {
      name: 'Виего (Величественно)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Сей путь оказался тернист. Я столкнулся со сложностями, которые невозможно решить при помощи силы и власти... ',
    },
    {
      name: 'Виего (Величественно)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Пришлось действовать иначе. Гвен добровольно помогала мне решать проблемы по мере их поступления, дабы выполнить условие уговора и... стать чу-чуть лучше. ',
    },
    {
      name: 'Виего (Величественно)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - По большей части, вам нужно благодарить ее. В одиночку я бы не справился!',
    },
    {
      name: 'Гвен (Уставшая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Да, %?"№;ь, это я!',
    },
    {
      name: 'Гвен (Уставшая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Держите меня...',
    },
    {
      name: 'Гвен (Падая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'right',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Мои RP...',
    },
    {
      name: 'Виего (Решившись)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Думаю, мы можем начинать.',
    },
    {
      name: 'Виего (Решившись)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Итак... Ривен!',
    },
    {
      name: 'Ривен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: RivenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' -  Да...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: RivenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' -  Я знаю, как тебе дорога Родина и не могу представить, через что тебе пришлось пройти перед возвращением. Своим подарком я хочу подчеркнуть уважение этой любви, поэтому вручаю тебе книгу...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: RivenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' -  Книгу о Де... Об Ионии. ',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: RivenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' -  Держи. ',
    },
    {
      name: 'Ривен (Удивленно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: RivenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' -  Что это? Кто такой Бесекерский...',
    },
    {
      name: 'Виего',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Идем дальше!',
    },
    {
      name: 'Виего',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Следующим шагом Гвен посоветовала мне порадовать нашу пушистую подругу...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Юми!',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Книга! Сейчас нам что-то подарят! Ух ты!',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' -  Юми, я понимаю, что ты, в первую очередь, кошка, а уже потом слот...',
    },
    {
      name: 'Юми',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Вообще-то я гуляю сама по себе!',
    },
    {
      name: 'Хасаге',
      secondPerson: true,
      isSecondMain: !true,
      image: HasagePlayNG,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Я тоже, хе-хе...',
    },
    {
      name: 'Самира',
      secondPerson: true,
      isSecondMain: true,
      image: HasagePlayNG,
      secondImage: SamiraNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ты продолжай, Виего, а я разберусь!',
    },
    {
      name: 'Виего (Благодарно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: SamiraNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Виего (Благодарно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: SamiraNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Спасибо, Самира. Твой подарок у меня тоже есть.',
    },
    {
      name: 'Юми (Любопытно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ну, что там с моим подарком, Призрак!?',
    },
    {
      name: 'Виего (Торжественно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Так вот... Юми, я дарю тебе...',
    },
    {
      name: 'Юми (Восхищенно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ух ты! КОРОБКА!!!',
    },
    {
      name: 'Юми (Вне себя от радости)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Виего! Это прекрасный подарок!!!',
    },
    {
      name: 'Юми (Любопытно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Так, тут внутри какая-то муть... Виего, спасибо больше! Я так давно хотела коробку! Я...',
    },
    {
      name: 'Виего (Растерянно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: CatNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Но...',
    },
    {
      name: 'Гарен',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GarenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Оставь ее, Виего. Пусть радуется.',
    },
    {
      name: 'Виего (Рассудительно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GarenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Хорошо, Гарен, тогда ты...',
    },
    {
      name: 'Виего (Рассудительно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GarenNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Итак, доблестное Сердце Демасии...',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ой, да что ты там, ;%)"ь, стрекочешь?',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: SamiraNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Самира!? Держи, тебе шляпу. Красивая. ковбойская - точно твой стиль.',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: YoneNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Генератор мудростей? Держи, тебе новую балалайку! Будешь, %:?№", играть нам... Am, Dm там... Сам знаешь!',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: GarenNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Гарен!? Там Дариус опять дунул в сторону Демасии! Вот тебе новые наплечники, которые больше, чем твоя голова! В бой!',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Рекетон? Ты вообще, №%:)?ь, в курсе, что мы тебя не понимаем?',
    },
    {
      name: 'Рекетон',
      secondPerson: true,
      isSecondMain: !true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Ар....?',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Самира не понимает твои истории. Она просто смеется между предложениями!',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Очнись! Вот тебе развивающий журнал для детей дошкольного возраста! Учи буквы!',
    },
    {
      name: 'Рекетон',
      secondPerson: true,
      isSecondMain: !true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Арррррра? Аррараррр?',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - ... ',
    },
    {
      name: 'Гвен (Восставшая из мертвых)',
      secondPerson: true,
      isSecondMain: true,
      image: ReketonNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Проехали. ',
    },
    {
      name: 'Гвен (Падая вновь)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Дальше сам.',
    },
    {
      name: 'Хасаге',
      secondPerson: true,
      isSecondMain: !true,
      image: HasagePlayNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - О, компания... Тебя с чего так...',
    },
    {
      name: 'Гвен (АФК)',
      secondPerson: true,
      isSecondMain: true,
      image: HasagePlayNG,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Виего (Смущенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Виего (Смущенно)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Она просто устала.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Гвен действительно помогала мне на протяжении всего пути, но один из подарков мне пришлось создать самому.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: GwenNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Мне обидно, что мои силы внушают страх. Этим подарком я хочу показать, что черный туман способен не только разрушать, но и создавать.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: SennaNG,
      position: 'center',
      secondPosition: 'left',
      bg: 'homeInside',
      text: ' - Я сотворил этот кулон и напитал его туманом. Элегантный, изящиный и, Сенна, он твой.',
    },
    {
      name: 'Люциан (резко)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Нет, она это не возьмет!  ',
    },
    {
      name: 'Сенна (Успокаивающе)',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: LucianNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Все в порядке, Люциан. Я ему верю.',
    },
    {
      name: 'Сенна (Успокаивающе)',
      secondPerson: true,
      isSecondMain: true,
      image: SennaNG,
      secondImage: LucianNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Плохая идея.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Люциан, мне кажется, мы уже достаточно сильны, чтобы перешагнуть наши обилды.',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Я верю, что мы можем быть друзьями, поэтому...',
    },
    {
      name: 'Люциан (Вздыхая)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - О, нет...',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Это именная пуля, даруется лучшему стрелку из всех, что я знаю и знал.',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Можешь застрелить меня из нее прямо сейчас, если считаешь врагом. Я сопротивляться не буду.',
    },
    {
      name: 'Люциан (Злостно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Люциан (Нкуверенно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Люциан (Сомнительно)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Люциан (Сдался)',
      secondPerson: true,
      isSecondMain: true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Ладно. Но не потому, что я тебя до конца простил, а просто потому, что пуля собой хороша!',
    },
    {
      name: 'Виего (Довольный)',
      secondPerson: true,
      isSecondMain: !true,
      image: Viego,
      secondImage: LucianNG,
      position: 'center',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Как скажешь, друг!',
    },
    {
      name: 'Сенна',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: LucianNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Молодец, Люциан. Я тобой горжусь.',
    },
    {
      name: 'Люциан',
      secondPerson: true,
      isSecondMain: true,
      image: SennaNG,
      secondImage: LucianNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Ага...',
    },
    {
      name: 'Сенна (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - И тобой тоже, Виего. Ты доказал, что мы не ошибись.',
    },
    {
      name: 'Сенна (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - И Изольда...',
    },
    {
      name: 'Сенна (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Она бы гордилась тобой.',
    },
    {
      name: 'Виего (Печально)',
      secondPerson: true,
      isSecondMain: true,
      image: SennaNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Надеюсь.',
    },
    {
      name: 'Гвен (Очнувшись)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Она бы точно гордилась!',
    },
    {
      name: 'Гвен (Очнувшись)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Ты подарил всем... большей части такие перкрасные подарки!',
    },
    {
      name: 'Самира (Прмеряя)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: SamiraNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Прекрасная шляпа, Королек! Так держать!',
    },
    {
      name: 'Юми (Играясь)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: CatNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Коробка-Коробка-Коробка!',
    },
    {
      name: 'Гарен (Красуясь)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: GarenNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - С такой-то броней Демасии ГАРЕНтированн покой! Спасибо, Виего!',
    },
    {
      name: 'Ёне (Увлеченно)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: YoneNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я сижууу и смотрю в чужое небо из чужого окнааа...',
    },
    {
      name: 'Ривен (Возмущенно)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: RivenNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - АЧХ, ФЧХ... Что, %);*ь!?',
    },
    {
      name: 'Рекетон (Увлеченно)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: ReketonNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - А - Аррррр, Б - Аррррр, В - АРРРРРР!',
    },
    {
      name: 'Гвен (Радостно)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Виего, ты не просто выполнил свой уговор, ты стал другим человеком!',
    },
    {
      name: 'Гвен (Радостно)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я уверена, будь Изольда сейчас среди нас, она бы тобой гордилась! Молодец, Виего! Молодец!',
    },
    {
      name: 'Все (Радостно)',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - Молодец, Виего! Молодец!',
    },
    {
      name: 'Виего',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Я... Что это?',
    },
    {
      name: 'Виего (Искренне)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Что это за чувство?',
    },
    {
      name: 'Виего (Искренне)',
      image: Viego,
      position: 'center',
      bg: 'homeInside',
      text: ' - Я... так рад...',
    },
    {
      name: 'Все (Радостно)',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - Молодец, Виего! Молодец!',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я...',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я... еще не закончил!',
    },
    {
      name: 'Все',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - ?',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я сделал первый шаг, но, безусловно, это еще не конец пути.',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я благодарен вам всем, за то, что поверили в меня, за предоставленный шанс и предстоящий праздник, но...',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Но подарок должны получить все. Особенно та, кто сопросождала меня на протяжении всего пути!',
    },
    {
      name: 'Виего (Искренне)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Та, кто поверила в меня и вселила веру в других, которая направляла, когда я сворачивал не туда...',
    },
    {
      name: 'Гвен (Удивленно)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Виего, мы же просто сходили в магазин.',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Это больше, чем просто магазин. Это начало нового пути! И, дабы подчеркнуть его значимость, я хочу подарить тебе кое-что от себя.',
    },
    {
      name: 'Гвен (Удивленно)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Виего! Это же...',
    },
    {
      name: 'Виего',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Я знаю. Изольда подарила мне эту шкатулку, но я хочу, чтобы она была у тебя.',
    },
    {
      name: 'Виего (Добро)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - В память о хороших временах.',
    },
    {
      name: 'Гвен (растерянно)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Виего...',
    },
    {
      name: 'Гвен (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: Viego,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Спасибо.',
    },
    {
      name: 'Ривен',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: RivenNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Ребята, осталось несколько минут!',
    },
    {
      name: 'Гвен (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: RivenNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Итак, Виего! Ты Сдержал свое слово и смог порадовать всех. В знак примерения и рождения нового начала...',
    },
    {
      name: 'Гвен (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: ViegoNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - ...',
    },
    {
      name: 'Гвен (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: ViegoNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Ты награжденшься это замечательной шапкой новогоднего дома Рунтерры! С этого дня наши двери открыты.',
    },
    {
      name: 'Гвен (Искренне)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: ViegoNG,
      position: 'left',
      secondPosition: 'right',
      bg: 'homeInside',
      text: ' - Будь как дома, мы не в чем тебе не откажем!',
    },
    {
      name: 'Все',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - Ураа!!!',
    },
    {
      name: 'Виего (Искренне)',
      image: ViegoNG,
      position: 'center',
      bg: 'homeInside',
      text: ' - Друзья... Я польщен.',
    },
    {
      name: 'Юми',
      image: CatNG,
      position: 'center',
      bg: 'homeInside',
      text: ' - Коробка, скоро будут удары часов!',
    },
    {
      name: 'Ривен',
      image: RivenNG,
      position: 'right',
      bg: 'homeInside',
      text: ' - Идемте к столу! Вот-вот начнется следующий год!',
    },
    {
      name: 'Сенна',
      secondPerson: true,
      isSecondMain: !true,
      image: SennaNG,
      secondImage: ReketonNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Будь как дома, мы не в чем тебе не откажем!',
    },
    {
      name: 'Рекетон (Радостно)',
      secondPerson: true,
      isSecondMain: true,
      image: SennaNG,
      secondImage: ReketonNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' -ВРАААААВ!',
    },
    {
      name: 'Гвен (В предвкушении)',
      secondPerson: true,
      isSecondMain: !true,
      image: GwenNG,
      secondImage: ViegoNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Пойдемте! Осталось совсем чуть-чуть!',
    },
    {
      name: 'Виего (Задорно)',
      secondPerson: true,
      isSecondMain: true,
      image: GwenNG,
      secondImage: ViegoNG,
      position: 'left',
      secondPosition: 'center',
      bg: 'homeInside',
      text: ' - Не будем медлить!',
    },
    {
      name: 'Все',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - 3...',
    },
    {
      name: 'Все',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - 2...',
    },
    {
      name: 'Все',
      image: allNG,
      position: 'full',
      bg: 'homeInside',
      text: ' - 1...',
    },
  ],
};

export const storySlice = createSlice({
  name: 'Answer',
  initialState,
  reducers: {},
});

export default storySlice.reducer;
